apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmdb
  labels:
    app: cmdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmdb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cmdb
    spec:
      volumes:
        - name: idoit-upload
          persistentVolumeClaim:
            claimName: idoit-upload
        - name: idoit-src
          persistentVolumeClaim:
            claimName: idoit-src
      containers:
        - name: cmdb
          image: 'jurikaur/i-doit:1.19'
          ports:
            - name: cmdb
              containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  key: TZ
                  name: env
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html/i-doit/src
              name: idoit-src
            - mountPath: /var/www/html/i-doit/upload
              name: idoit-upload