apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: idoit-upload
  name: idoit-upload
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
status: {}