apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: idoit-src
  name: idoit-src
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
status: {}